name: nanopore_covid
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.6.10
  - conda-forge::r-base=3.6.2
  - conda-forge::r-tidyr=1.1.0
  - conda-forge::r-tidyverse=1.3.0
  - conda-forge::r-ggplot2=3.3.1
  - conda-forge::r-reshape2=1.4.4
  - conda-forge::r-viridis=0.5.1
  - bioconda::fastqc=0.11.9
  - bioconda::sra-tools=2.10.7
  - bioconda::fastp=0.20.1
  - bioconda::samtools=1.9
  - bioconda::bedtools=2.29.2
  - bioconda::multiqc=1.9
  - bioconda::picard=2.23.0
  - bioconda::mosdepth=0.2.6
  - bioconda::ivar=1.2.2
  - bioconda::bcftools=1.9
  - bioconda::varscan=2.4.4
  - bioconda::snpeff=4.5covid19
  - bioconda::snpsift=4.3.1t
  - bioconda::bioconductor-complexheatmap=2.2.0
  - bioconda::cutadapt=2.10
  - bioconda::kraken2=2.0.9beta
  - bioconda::minimap2=2.17
